# Introdução

Este notebook foi feito por Gabriel Matz visando o estudo dirigido para a prova de certificação oficial para o Tensorflow. A descrição da prova está no seguinte link:
https://www.tensorflow.org/certificate?hl=pt-br.

Utilizei como base os seguintes notebooks(além de sites variados e stack overflow para pequenas consultas):

1- https://github.com/mrdbourke/tensorflow-deep-learning

2-https://github.com/williamcwi/DeepLearning.AI-TensorFlow-Developer-Professional-Certificate

O conteúdo deste primeiro notebook engloba a primeira parte de exigências da prova do Tensorflow, que estão descritas abaixo:

"
(1) Habilidades de Desenvolvedor TensorFlow

Você precisa demonstrar que entende como desenvolver programas de software usando TensorFlow e que consegue encontrar as informações necessárias para trabalhar como um profissional de aprendizado de máquina. Você precisa:

❏ Saber programar em Python, resolver problemas em Python e compilar e executar programas Python no PyCharm.

❏ Saber como encontrar informações sobre as APIs do TensorFlow, incluindo como encontrar guias e referências de API em tensorflow.org.

❏ Saber como depurar, investigar e resolver mensagens de erro provenientes da API do TensorFlow.

❏ Saber como procurar além do tensorflow.org, quando necessário, para resolver suas dúvidas sobre o TensorFlow.

❏ Saber como criar modelos de aprendizado de máquina usando TensorFlow, onde o tamanho do modelo seja razoável para o problema sendo resolvido.

❏ Saber como salvar modelos de aprendizado de máquina e verificar o tamanho do arquivo do modelo.

❏ Entender as discrepâncias de compatibilidade entre diferentes versões do TensorFlow."

# Desenvolvimento

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.15.0


**"❏ Saber programar em Python, resolver problemas em Python e compilar e executar programas Python no PyCharm."**

Para realizar a prova é necessário a IDE do Pycharm.

Link download: https://www.jetbrains.com/pycharm/download/?section=windows

**"❏ Saber como encontrar informações sobre as APIs do TensorFlow, incluindo como encontrar guias e referências de API em tensorflow.org."**

https://www.tensorflow.org/api_docs/python/

Lista todas as funções e bibliotecas que podem ser úteis

**"❏ Saber como depurar, investigar e resolver mensagens de erro provenientes da API do TensorFlow."**

O Tensorflow oferece diversas ferramentas de debugging, cito aqui as 2 que achei mais úteis:

1- tf.print

O argumento output_stream indica para onde será enviado a mensagem, como stdout,stderr, algum arquivo...

In [ ]:
import sys
@tf.function
def f():
    tensor = tf.range(10)
    tf.print(tensor,
             output_stream=sys.stdout)
    return tensor

range_tensor = f()

[0 1 2 ... 7 8 9]


2- tf.debugging

Contém uma série de funções úteis para debugging simples.

 https://www.tensorflow.org/api_docs/python/tf/debugging

In [ ]:
# Exemplo
def check_size(x):
  with tf.control_dependencies([
      tf.debugging.assert_equal(tf.size(x), 3,
                      message='Bad tensor size')]):
    return x
check_size(tf.ones([2, 3], tf.float32))

InvalidArgumentError: Bad tensor size
Condition x == y did not hold.
First 1 elements of x:
[6]
First 1 elements of y:
[3]

**"❏ Saber como procurar além do tensorflow.org, quando necessário, para resolver suas dúvidas sobre o TensorFlow."**

Links úteis para dúvidas:

1- Comunidade do tensorflow: https://www.tensorflow.org/community?hl=pt-br

2- Stack overflow: https://stackoverflow.com/

3- Git do Tensorflow: https://github.com/tensorflow/tensorflow


**"❏ Saber como criar modelos de aprendizado de máquina usando TensorFlow, onde o tamanho do modelo seja razoável para o problema sendo resolvido."**


Será tratado nos próximos notebooks.

**"❏ Saber como salvar modelos de aprendizado de máquina e verificar o tamanho do arquivo do modelo."**

Existem 3 formas de salvar modelos com o tensorflow, exemplos práticos ficarão para os próximos notebooks.

https://www.tensorflow.org/tutorials/keras/save_and_load?hl=pt-br

1- .save

Gera uma cópia na forma SavedModel. Para entender melhor as vantagens e desvantagens:

https://www.tensorflow.org/guide/saved_model?hl=pt-br

É um formato único ao Tensorflow, portanto não compatível com outros frameworks.

2- .hdf5

Forma padronizada de salvar grandes quantidades de dados, compatível com outros frameworks

3- Salvar só os pesos
Será tratado nos próximos notebooks.


**"❏ Entender as discrepâncias de compatibilidade entre diferentes versões do TensorFlow."**

O Tensorflow passou por muitas mudanças durante os últimos 5 anos, então é muito comum encontrar códigos de 2/3 anos atrás que não funcionam mais. Busque sempre referências de 2022 pra frente.

Para mais informações leia a API.

**Extra: TensorFlowPlaygroung**

https://playground.tensorflow.org/

Excelente ferramenta para quem está começando a aprender redes neurais.

# Trabalhando com tensores e matrizes



Utilizar tensores com o tensorflow oferece uma vantagem quando comparado com o numpy: a capacidade de utilizar GPUs. Os dois frameworks trabalham bem juntos, tendo diversas funções a mesma sintaxe. Nesta seção irei listar as funções mais importantes.


In [ ]:
import numpy as np

**Tensores constantes**

Como o próprio nome diz, seus valores são imutáveis.

In [ ]:
# Matriz simples com tf.constant
matriz = tf.constant([[7., 0.],
                      [1., 10.]])
matriz

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7.,  0.],
       [ 1., 10.]], dtype=float32)>

In [ ]:
# Verificar dimensões
matriz.ndim

2

In [ ]:
# Definir o tipo de dados pode ser útil para otimização. Por padrão é int 32 ou float32.
matriz_2 = tf.constant([[10., 7., 9.],
                        [8., 1., 0.]],
                        dtype=tf.float16) # especificando o dtype
matriz_2

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  7.,  9.],
       [ 8.,  1.,  0.]], dtype=float16)>

In [ ]:
# Tensor de 3 dimensões = matriz 3D :O
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Tensor de zeros
tf.zeros(shape=(3, 8))

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Tensor de 1
tf.ones(shape=(3, 1))

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

**Tensores variáveis**

Como o próprio nome diz, seus valores são mutáveis.

In [ ]:
tensor_2= tf.Variable([[1., 2.],
                       [0., 0.],
                       [4., 4.]])
# É necessário usar .assign para mudar o valor
tensor_2[1].assign(2)
tensor_2.numpy()

array([[1., 2.],
       [2., 2.],
       [4., 4.]], dtype=float32)

In [ ]:
tensor_2.assign_add([[1., 2.], [0., 0. ], [1., 1.]]) # adiciona elemento por elemento

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=float32, numpy=
array([[2., 4.],
       [2., 2.],
       [5., 5.]], dtype=float32)>

**Tensores randômicos**

In [ ]:
# Caso você queira que os resultados se mantenham reproduzíveis, não se esqueça de usar uma seed
random_1 = tf.random.Generator.from_seed(1) # seed
random_1 = random_1.normal(shape=(3, 5)) # usando distribuição normal
random_2 = tf.random.Generator.from_seed(1)
random_2 = random_2.normal(shape=(3, 5))

random_1, random_2

(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[ 0.43842277, -0.53439844, -0.07710262,  1.5658045 , -0.1012345 ],
        [-0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ,  1.0019135 ,  0.67351365,  0.06987712]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[ 0.43842277, -0.53439844, -0.07710262,  1.5658045 , -0.1012345 ],
        [-0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924, -1.9633987 ],
        [-0.06452483, -1.056841  ,  1.0019135 ,  0.67351365,  0.06987712]],
       dtype=float32)>)

**Shuffle**

Pode ser útil em data augmentation(aumento de dados)

In [ ]:
tf.random.shuffle(random_1, seed=1)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[ 0.43842277, -0.53439844, -0.07710262,  1.5658045 , -0.1012345 ],
       [-0.06452483, -1.056841  ,  1.0019135 ,  0.67351365,  0.06987712],
       [-0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924, -1.9633987 ]],
      dtype=float32)>

**Indexing e outras informações**

In [ ]:
# "Geometria" do tensor
random_1.shape, random_1.ndim, tf.size(random_1)

(TensorShape([3, 5]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=15>)

In [ ]:
# Trabalhar com índices é igual ao Numpy
random_1[:2, :4]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.43842277, -0.53439844, -0.07710262,  1.5658045 ],
       [-0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924]],
      dtype=float32)>

In [ ]:
# Para expandir dimensões
tf.expand_dims(random_1, axis=2)

<tf.Tensor: shape=(3, 5, 1), dtype=float32, numpy=
array([[[ 0.43842277],
        [-0.53439844],
        [-0.07710262],
        [ 1.5658045 ],
        [-0.1012345 ]],

       [[-0.2744976 ],
        [ 1.4204658 ],
        [ 1.2609464 ],
        [-0.43640924],
        [-1.9633987 ]],

       [[-0.06452483],
        [-1.056841  ],
        [ 1.0019135 ],
        [ 0.67351365],
        [ 0.06987712]]], dtype=float32)>

**Operações com tensores**

In [ ]:
# Básicas
random_1 + 1, random_1*10, random_1 - 2

(<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[ 1.4384228 ,  0.46560156,  0.9228974 ,  2.5658045 ,  0.8987655 ],
        [ 0.7255024 ,  2.420466  ,  2.2609463 ,  0.56359076, -0.9633987 ],
        [ 0.9354752 , -0.05684102,  2.0019135 ,  1.6735137 ,  1.0698771 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[  4.3842278 ,  -5.3439846 ,  -0.77102613,  15.658045  ,
          -1.0123451 ],
        [ -2.744976  ,  14.2046585 ,  12.609464  ,  -4.3640924 ,
         -19.633987  ],
        [ -0.6452483 , -10.56841   ,  10.019135  ,   6.7351365 ,
           0.6987712 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 5), dtype=float32, numpy=
 array([[-1.5615772 , -2.5343986 , -2.0771027 , -0.43419552, -2.1012344 ],
        [-2.2744975 , -0.5795342 , -0.7390536 , -2.4364092 , -3.9633987 ],
        [-2.064525  , -3.056841  , -0.99808645, -1.3264863 , -1.9301229 ]],
       dtype=float32)>)

In [ ]:
# Pode ser usado também as funções próprias do tensorflow
tf.multiply(random_1, 10)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[  4.3842278 ,  -5.3439846 ,  -0.77102613,  15.658045  ,
         -1.0123451 ],
       [ -2.744976  ,  14.2046585 ,  12.609464  ,  -4.3640924 ,
        -19.633987  ],
       [ -0.6452483 , -10.56841   ,  10.019135  ,   6.7351365 ,
          0.6987712 ]], dtype=float32)>

In [ ]:
# As matrizes tem tamanhos incompativeis para mult. Para ajeitar o tamanho:
random_2=tf.reshape(random_2, shape=(5, 3))
random_2

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 0.43842277, -0.53439844, -0.07710262],
       [ 1.5658045 , -0.1012345 , -0.2744976 ],
       [ 1.4204658 ,  1.2609464 , -0.43640924],
       [-1.9633987 , -0.06452483, -1.056841  ],
       [ 1.0019135 ,  0.67351365,  0.06987712]], dtype=float32)>

In [ ]:
tf.matmul(random_1, random_2)

In [ ]:
# Transposição
tf.transpose(random_1)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 0.43842277, -0.2744976 , -0.06452483],
       [-0.53439844,  1.4204658 , -1.056841  ],
       [-0.07710262,  1.2609464 ,  1.0019135 ],
       [ 1.5658045 , -0.43640924,  0.67351365],
       [-0.1012345 , -1.9633987 ,  0.06987712]], dtype=float32)>

In [ ]:
tf.sqrt(tf.abs(random_1)) # raiz quadrada

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.662135  , 0.7310256 , 0.27767357, 1.2513211 , 0.3181737 ],
       [0.5239252 , 1.1918329 , 1.1229187 , 0.66061276, 1.4012133 ],
       [0.25401738, 1.0280278 , 1.0009563 , 0.8206788 , 0.2643428 ]],
      dtype=float32)>

**Mudança de dados**

In [ ]:
A= tf.constant([1, 2])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
B= tf.cast(A, dtype=tf.float16) # Vai ser útil mudar o dtype posteriormente
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>

**Máximos, mínimos e módulo**


In [ ]:
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
tf.abs(A) # valor absoluto

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
tf.reduce_max(A) # máximo global

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.reduce_min(A) # mínimo global

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.reduce_mean(A) # média

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.reduce_sum(A) # soma dos elementos

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.argmax(A) #posição do máximo

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.argmin(A) #posição do mínimo

<tf.Tensor: shape=(), dtype=int64, numpy=0>

**Squeeze**

Retira dimensões = 1

In [ ]:
C = tf.constant(np.random.randint(0, 1000, 50), shape=(1, 1, 1, 50))
C.shape, C.ndim

(TensorShape([1, 1, 1, 50]), 4)

In [ ]:
C_squeezed = tf.squeeze(C)
C_squeezed.shape, C_squeezed.ndim

(TensorShape([50]), 1)

**Decorador**

Para entender as vantagens do decorador, leia abaixo:
https://www.tensorflow.org/guide/function?hl=pt-br

Basicamente:
A função dessa forma gera gráficos, que capturados fornecem dois benefícios:

1- Aceleração significativa na execução.

2- Exportar esses gráficos, usando tf.saved_model , para executar em outros sistemas como um servidor ou um dispositivo móvel , sem necessidade de instalação do Python.

In [ ]:
@tf.function
def tf_function(x, y):
  return x ** 2 + y
